set_property SRC_FILE_INFO {cfile:F:/Learning/CPU/GitHub/cpu/cpu/cpu.srcs/constrs_1/new/001.xdc rfile:../../../cpu.srcs/constrs_1/new/001.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports BasysCLK]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {bits[3]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {bits[2]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {bits[1]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {bits[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {segOut[6]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {segOut[3]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {segOut[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {SW_in[1]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {SW_in[0]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports RST]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {segOut[7]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {segOut[1]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {segOut[2]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {segOut[4]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {segOut[5]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports CLKButton]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu/DBOut[0]} {cpu/DBOut[1]} {cpu/DBOut[2]} {cpu/DBOut[3]} {cpu/DBOut[4]} {cpu/DBOut[5]} {cpu/DBOut[6]} {cpu/DBOut[7]} {cpu/DBOut[8]} {cpu/DBOut[9]} {cpu/DBOut[10]} {cpu/DBOut[11]} {cpu/DBOut[12]} {cpu/DBOut[13]} {cpu/DBOut[14]} {cpu/DBOut[15]} {cpu/DBOut[16]} {cpu/DBOut[17]} {cpu/DBOut[18]} {cpu/DBOut[19]} {cpu/DBOut[20]} {cpu/DBOut[21]} {cpu/DBOut[22]} {cpu/DBOut[23]} {cpu/DBOut[24]} {cpu/DBOut[25]} {cpu/DBOut[26]} {cpu/DBOut[27]} {cpu/DBOut[28]} {cpu/DBOut[29]} {cpu/DBOut[30]} {cpu/DBOut[31]}]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[9]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[11]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[15]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[16]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[26]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[10]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[8]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[14]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[17]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[20]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[21]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[23]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[28]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[12]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[13]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[18]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[19]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[29]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[30]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[22]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[24]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[25]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[27]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ALUout[31]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list BasysCLK_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu/PCNowOut[0]} {cpu/PCNowOut[1]} {cpu/PCNowOut[2]} {cpu/PCNowOut[3]} {cpu/PCNowOut[4]} {cpu/PCNowOut[5]} {cpu/PCNowOut[6]} {cpu/PCNowOut[7]} {cpu/PCNowOut[8]} {cpu/PCNowOut[9]} {cpu/PCNowOut[10]} {cpu/PCNowOut[11]} {cpu/PCNowOut[12]} {cpu/PCNowOut[13]} {cpu/PCNowOut[14]} {cpu/PCNowOut[15]} {cpu/PCNowOut[16]} {cpu/PCNowOut[17]} {cpu/PCNowOut[18]} {cpu/PCNowOut[19]} {cpu/PCNowOut[20]} {cpu/PCNowOut[21]} {cpu/PCNowOut[22]} {cpu/PCNowOut[23]} {cpu/PCNowOut[24]} {cpu/PCNowOut[25]} {cpu/PCNowOut[26]} {cpu/PCNowOut[27]} {cpu/PCNowOut[28]} {cpu/PCNowOut[29]} {cpu/PCNowOut[30]} {cpu/PCNowOut[31]}]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu/PC4[0]} {cpu/PC4[1]} {cpu/PC4[2]} {cpu/PC4[3]} {cpu/PC4[4]} {cpu/PC4[5]} {cpu/PC4[6]} {cpu/PC4[7]} {cpu/PC4[8]} {cpu/PC4[9]} {cpu/PC4[10]} {cpu/PC4[11]} {cpu/PC4[12]} {cpu/PC4[13]} {cpu/PC4[14]} {cpu/PC4[15]} {cpu/PC4[16]} {cpu/PC4[17]} {cpu/PC4[18]} {cpu/PC4[19]} {cpu/PC4[20]} {cpu/PC4[21]} {cpu/PC4[22]} {cpu/PC4[23]} {cpu/PC4[24]} {cpu/PC4[25]} {cpu/PC4[26]} {cpu/PC4[27]} {cpu/PC4[28]} {cpu/PC4[29]} {cpu/PC4[30]} {cpu/PC4[31]}]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu/PC4Out[0]} {cpu/PC4Out[1]} {cpu/PC4Out[2]} {cpu/PC4Out[3]} {cpu/PC4Out[4]} {cpu/PC4Out[5]} {cpu/PC4Out[6]} {cpu/PC4Out[7]} {cpu/PC4Out[8]} {cpu/PC4Out[9]} {cpu/PC4Out[10]} {cpu/PC4Out[11]} {cpu/PC4Out[12]} {cpu/PC4Out[13]} {cpu/PC4Out[14]} {cpu/PC4Out[15]} {cpu/PC4Out[16]} {cpu/PC4Out[17]} {cpu/PC4Out[18]} {cpu/PC4Out[19]} {cpu/PC4Out[20]} {cpu/PC4Out[21]} {cpu/PC4Out[22]} {cpu/PC4Out[23]} {cpu/PC4Out[24]} {cpu/PC4Out[25]} {cpu/PC4Out[26]} {cpu/PC4Out[27]} {cpu/PC4Out[28]} {cpu/PC4Out[29]} {cpu/PC4Out[30]} {cpu/PC4Out[31]}]]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {DBOut[0]} {DBOut[1]} {DBOut[2]} {DBOut[3]} {DBOut[4]} {DBOut[5]} {DBOut[6]} {DBOut[7]} {DBOut[8]} {DBOut[9]} {DBOut[10]} {DBOut[11]} {DBOut[12]} {DBOut[13]} {DBOut[14]} {DBOut[15]} {DBOut[16]} {DBOut[17]} {DBOut[18]} {DBOut[19]} {DBOut[20]} {DBOut[21]} {DBOut[22]} {DBOut[23]} {DBOut[24]} {DBOut[25]} {DBOut[26]} {DBOut[27]} {DBOut[28]} {DBOut[29]} {DBOut[30]} {DBOut[31]}]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {cpu/RsAddr[0]} {cpu/RsAddr[1]} {cpu/RsAddr[2]} {cpu/RsAddr[3]} {cpu/RsAddr[4]}]]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu/ALUOut[0]} {cpu/ALUOut[1]} {cpu/ALUOut[2]} {cpu/ALUOut[3]} {cpu/ALUOut[4]} {cpu/ALUOut[5]} {cpu/ALUOut[6]} {cpu/ALUOut[7]} {cpu/ALUOut[8]} {cpu/ALUOut[9]} {cpu/ALUOut[10]} {cpu/ALUOut[11]} {cpu/ALUOut[12]} {cpu/ALUOut[13]} {cpu/ALUOut[14]} {cpu/ALUOut[15]} {cpu/ALUOut[16]} {cpu/ALUOut[17]} {cpu/ALUOut[18]} {cpu/ALUOut[19]} {cpu/ALUOut[20]} {cpu/ALUOut[21]} {cpu/ALUOut[22]} {cpu/ALUOut[23]} {cpu/ALUOut[24]} {cpu/ALUOut[25]} {cpu/ALUOut[26]} {cpu/ALUOut[27]} {cpu/ALUOut[28]} {cpu/ALUOut[29]} {cpu/ALUOut[30]} {cpu/ALUOut[31]}]]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {ALUout[0]} {ALUout[1]} {ALUout[2]} {ALUout[3]} {ALUout[4]} {ALUout[5]} {ALUout[6]} {ALUout[7]} {ALUout[8]} {ALUout[9]} {ALUout[10]} {ALUout[11]} {ALUout[12]} {ALUout[13]} {ALUout[14]} {ALUout[15]} {ALUout[16]} {ALUout[17]} {ALUout[18]} {ALUout[19]} {ALUout[20]} {ALUout[21]} {ALUout[22]} {ALUout[23]} {ALUout[24]} {ALUout[25]} {ALUout[26]} {ALUout[27]} {ALUout[28]} {ALUout[29]} {ALUout[30]} {ALUout[31]}]]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {cpu/RtAddr[0]} {cpu/RtAddr[1]} {cpu/RtAddr[2]} {cpu/RtAddr[3]} {cpu/RtAddr[4]}]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {cpu/ALUout[0]} {cpu/ALUout[1]} {cpu/ALUout[2]} {cpu/ALUout[3]} {cpu/ALUout[4]} {cpu/ALUout[5]} {cpu/ALUout[6]} {cpu/ALUout[7]} {cpu/ALUout[8]}]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list CPUCLK]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets BasysCLK_IBUF_BUFG]
