set_property IOSTANDARD LVCMOS33 [get_ports {segOut[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports BasysCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CPUCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN W5 [get_ports BasysCLK]
set_property PACKAGE_PIN T17 [get_ports CPUCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CPUCLK]


set_property IOSTANDARD LVCMOS33 [get_ports {bits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[0]}]
set_property PACKAGE_PIN U2 [get_ports {bits[3]}]
set_property PACKAGE_PIN U4 [get_ports {bits[2]}]
set_property PACKAGE_PIN V4 [get_ports {bits[1]}]
set_property PACKAGE_PIN W4 [get_ports {bits[0]}]
set_property PACKAGE_PIN U7 [get_ports {segOut[6]}]
set_property PACKAGE_PIN V8 [get_ports {segOut[3]}]
set_property PACKAGE_PIN W7 [get_ports {segOut[0]}]
set_property PACKAGE_PIN R2 [get_ports {SW_in[1]}]
set_property PACKAGE_PIN T1 [get_ports {SW_in[0]}]
set_property PACKAGE_PIN V17 [get_ports RST]

set_property PACKAGE_PIN V7 [get_ports {segOut[7]}]
set_property PACKAGE_PIN W6 [get_ports {segOut[1]}]
set_property PACKAGE_PIN U8 [get_ports {segOut[2]}]
set_property PACKAGE_PIN U5 [get_ports {segOut[4]}]
set_property PACKAGE_PIN V5 [get_ports {segOut[5]}]
