set_property IOSTANDARD LVCMOS33 [get_ports {segOut[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports BasysCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN W5 [get_ports BasysCLK]


set_property IOSTANDARD LVCMOS33 [get_ports {bits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bits[0]}]
set_property PACKAGE_PIN U2 [get_ports {bits[3]}]
set_property PACKAGE_PIN U4 [get_ports {bits[2]}]
set_property PACKAGE_PIN V4 [get_ports {bits[1]}]
set_property PACKAGE_PIN W4 [get_ports {bits[0]}]
set_property PACKAGE_PIN U7 [get_ports {segOut[6]}]
set_property PACKAGE_PIN V8 [get_ports {segOut[3]}]
set_property PACKAGE_PIN W7 [get_ports {segOut[0]}]
set_property PACKAGE_PIN R2 [get_ports {SW_in[1]}]
set_property PACKAGE_PIN T1 [get_ports {SW_in[0]}]
set_property PACKAGE_PIN V17 [get_ports RST]

set_property PACKAGE_PIN V7 [get_ports {segOut[7]}]
set_property PACKAGE_PIN W6 [get_ports {segOut[1]}]
set_property PACKAGE_PIN U8 [get_ports {segOut[2]}]
set_property PACKAGE_PIN U5 [get_ports {segOut[4]}]
set_property PACKAGE_PIN V5 [get_ports {segOut[5]}]




set_property PACKAGE_PIN T17 [get_ports CLKButton]
set_property IOSTANDARD LVCMOS33 [get_ports CLKButton]







set_property MARK_DEBUG false [get_nets {cpu/ALUout[10]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[12]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[13]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[15]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[19]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[24]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[27]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[28]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[9]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[18]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[20]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[22]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[25]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[17]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[21]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[23]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[26]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[29]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[30]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[31]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[11]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[14]}]
set_property MARK_DEBUG false [get_nets {cpu/ALUout[16]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[2]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[3]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[6]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[0]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[1]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[4]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[5]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[7]}]
set_property MARK_DEBUG true [get_nets {cpu/ALUout[8]}]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu/DBOut[0]} {cpu/DBOut[1]} {cpu/DBOut[2]} {cpu/DBOut[3]} {cpu/DBOut[4]} {cpu/DBOut[5]} {cpu/DBOut[6]} {cpu/DBOut[7]} {cpu/DBOut[8]} {cpu/DBOut[9]} {cpu/DBOut[10]} {cpu/DBOut[11]} {cpu/DBOut[12]} {cpu/DBOut[13]} {cpu/DBOut[14]} {cpu/DBOut[15]} {cpu/DBOut[16]} {cpu/DBOut[17]} {cpu/DBOut[18]} {cpu/DBOut[19]} {cpu/DBOut[20]} {cpu/DBOut[21]} {cpu/DBOut[22]} {cpu/DBOut[23]} {cpu/DBOut[24]} {cpu/DBOut[25]} {cpu/DBOut[26]} {cpu/DBOut[27]} {cpu/DBOut[28]} {cpu/DBOut[29]} {cpu/DBOut[30]} {cpu/DBOut[31]}]]
set_property MARK_DEBUG true [get_nets {DBOut[0]}]
set_property MARK_DEBUG true [get_nets {DBOut[1]}]
set_property MARK_DEBUG true [get_nets {DBOut[2]}]
set_property MARK_DEBUG true [get_nets {DBOut[3]}]
set_property MARK_DEBUG true [get_nets {DBOut[4]}]
set_property MARK_DEBUG true [get_nets {DBOut[5]}]
set_property MARK_DEBUG true [get_nets {DBOut[6]}]
set_property MARK_DEBUG true [get_nets {DBOut[7]}]
set_property MARK_DEBUG true [get_nets {ALUout[0]}]
set_property MARK_DEBUG true [get_nets {ALUout[1]}]
set_property MARK_DEBUG true [get_nets {ALUout[3]}]
set_property MARK_DEBUG true [get_nets {ALUout[9]}]
set_property MARK_DEBUG true [get_nets {ALUout[11]}]
set_property MARK_DEBUG true [get_nets {ALUout[15]}]
set_property MARK_DEBUG true [get_nets {ALUout[16]}]
set_property MARK_DEBUG true [get_nets {ALUout[26]}]
set_property MARK_DEBUG true [get_nets {ALUout[10]}]
set_property MARK_DEBUG true [get_nets {ALUout[6]}]
set_property MARK_DEBUG true [get_nets {ALUout[8]}]
set_property MARK_DEBUG true [get_nets {ALUout[14]}]
set_property MARK_DEBUG true [get_nets {ALUout[17]}]
set_property MARK_DEBUG true [get_nets {ALUout[20]}]
set_property MARK_DEBUG true [get_nets {ALUout[21]}]
set_property MARK_DEBUG true [get_nets {ALUout[23]}]
set_property MARK_DEBUG true [get_nets {ALUout[28]}]
set_property MARK_DEBUG true [get_nets {ALUout[2]}]
set_property MARK_DEBUG true [get_nets {ALUout[4]}]
set_property MARK_DEBUG true [get_nets {ALUout[12]}]
set_property MARK_DEBUG true [get_nets {ALUout[13]}]
set_property MARK_DEBUG true [get_nets {ALUout[18]}]
set_property MARK_DEBUG true [get_nets {ALUout[19]}]
set_property MARK_DEBUG true [get_nets {ALUout[29]}]
set_property MARK_DEBUG true [get_nets {ALUout[30]}]
set_property MARK_DEBUG true [get_nets {ALUout[5]}]
set_property MARK_DEBUG true [get_nets {ALUout[7]}]
set_property MARK_DEBUG true [get_nets {ALUout[22]}]
set_property MARK_DEBUG true [get_nets {ALUout[24]}]
set_property MARK_DEBUG true [get_nets {ALUout[25]}]
set_property MARK_DEBUG true [get_nets {ALUout[27]}]
set_property MARK_DEBUG true [get_nets {ALUout[31]}]

connect_debug_port u_ila_0/probe0 [get_nets [list {cpu/PCNowOut[0]} {cpu/PCNowOut[1]} {cpu/PCNowOut[2]} {cpu/PCNowOut[3]} {cpu/PCNowOut[4]} {cpu/PCNowOut[5]} {cpu/PCNowOut[6]} {cpu/PCNowOut[7]} {cpu/PCNowOut[8]} {cpu/PCNowOut[9]} {cpu/PCNowOut[10]} {cpu/PCNowOut[11]} {cpu/PCNowOut[12]} {cpu/PCNowOut[13]} {cpu/PCNowOut[14]} {cpu/PCNowOut[15]} {cpu/PCNowOut[16]} {cpu/PCNowOut[17]} {cpu/PCNowOut[18]} {cpu/PCNowOut[19]} {cpu/PCNowOut[20]} {cpu/PCNowOut[21]} {cpu/PCNowOut[22]} {cpu/PCNowOut[23]} {cpu/PCNowOut[24]} {cpu/PCNowOut[25]} {cpu/PCNowOut[26]} {cpu/PCNowOut[27]} {cpu/PCNowOut[28]} {cpu/PCNowOut[29]} {cpu/PCNowOut[30]} {cpu/PCNowOut[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu/PC4Out[0]} {cpu/PC4Out[1]} {cpu/PC4Out[2]} {cpu/PC4Out[3]} {cpu/PC4Out[4]} {cpu/PC4Out[5]} {cpu/PC4Out[6]} {cpu/PC4Out[7]} {cpu/PC4Out[8]} {cpu/PC4Out[9]} {cpu/PC4Out[10]} {cpu/PC4Out[11]} {cpu/PC4Out[12]} {cpu/PC4Out[13]} {cpu/PC4Out[14]} {cpu/PC4Out[15]} {cpu/PC4Out[16]} {cpu/PC4Out[17]} {cpu/PC4Out[18]} {cpu/PC4Out[19]} {cpu/PC4Out[20]} {cpu/PC4Out[21]} {cpu/PC4Out[22]} {cpu/PC4Out[23]} {cpu/PC4Out[24]} {cpu/PC4Out[25]} {cpu/PC4Out[26]} {cpu/PC4Out[27]} {cpu/PC4Out[28]} {cpu/PC4Out[29]} {cpu/PC4Out[30]} {cpu/PC4Out[31]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list BasysCLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu/ALUDataA[0]} {cpu/ALUDataA[1]} {cpu/ALUDataA[2]} {cpu/ALUDataA[3]} {cpu/ALUDataA[4]} {cpu/ALUDataA[5]} {cpu/ALUDataA[6]} {cpu/ALUDataA[7]} {cpu/ALUDataA[8]} {cpu/ALUDataA[9]} {cpu/ALUDataA[10]} {cpu/ALUDataA[11]} {cpu/ALUDataA[12]} {cpu/ALUDataA[13]} {cpu/ALUDataA[14]} {cpu/ALUDataA[15]} {cpu/ALUDataA[16]} {cpu/ALUDataA[17]} {cpu/ALUDataA[18]} {cpu/ALUDataA[19]} {cpu/ALUDataA[20]} {cpu/ALUDataA[21]} {cpu/ALUDataA[22]} {cpu/ALUDataA[23]} {cpu/ALUDataA[24]} {cpu/ALUDataA[25]} {cpu/ALUDataA[26]} {cpu/ALUDataA[27]} {cpu/ALUDataA[28]} {cpu/ALUDataA[29]} {cpu/ALUDataA[30]} {cpu/ALUDataA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 9 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu/ALUout[0]} {cpu/ALUout[1]} {cpu/ALUout[2]} {cpu/ALUout[3]} {cpu/ALUout[4]} {cpu/ALUout[5]} {cpu/ALUout[6]} {cpu/ALUout[7]} {cpu/ALUout[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu/ALUDataB[0]} {cpu/ALUDataB[1]} {cpu/ALUDataB[2]} {cpu/ALUDataB[3]} {cpu/ALUDataB[4]} {cpu/ALUDataB[5]} {cpu/ALUDataB[6]} {cpu/ALUDataB[7]} {cpu/ALUDataB[8]} {cpu/ALUDataB[9]} {cpu/ALUDataB[10]} {cpu/ALUDataB[11]} {cpu/ALUDataB[12]} {cpu/ALUDataB[13]} {cpu/ALUDataB[14]} {cpu/ALUDataB[15]} {cpu/ALUDataB[16]} {cpu/ALUDataB[17]} {cpu/ALUDataB[18]} {cpu/ALUDataB[19]} {cpu/ALUDataB[20]} {cpu/ALUDataB[21]} {cpu/ALUDataB[22]} {cpu/ALUDataB[23]} {cpu/ALUDataB[24]} {cpu/ALUDataB[25]} {cpu/ALUDataB[26]} {cpu/ALUDataB[27]} {cpu/ALUDataB[28]} {cpu/ALUDataB[29]} {cpu/ALUDataB[30]} {cpu/ALUDataB[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {cpu/ALUOut[0]} {cpu/ALUOut[1]} {cpu/ALUOut[2]} {cpu/ALUOut[3]} {cpu/ALUOut[4]} {cpu/ALUOut[5]} {cpu/ALUOut[6]} {cpu/ALUOut[7]} {cpu/ALUOut[8]} {cpu/ALUOut[9]} {cpu/ALUOut[10]} {cpu/ALUOut[11]} {cpu/ALUOut[12]} {cpu/ALUOut[13]} {cpu/ALUOut[14]} {cpu/ALUOut[15]} {cpu/ALUOut[16]} {cpu/ALUOut[17]} {cpu/ALUOut[18]} {cpu/ALUOut[19]} {cpu/ALUOut[20]} {cpu/ALUOut[21]} {cpu/ALUOut[22]} {cpu/ALUOut[23]} {cpu/ALUOut[24]} {cpu/ALUOut[25]} {cpu/ALUOut[26]} {cpu/ALUOut[27]} {cpu/ALUOut[28]} {cpu/ALUOut[29]} {cpu/ALUOut[30]} {cpu/ALUOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 5 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {cpu/RsAddr[0]} {cpu/RsAddr[1]} {cpu/RsAddr[2]} {cpu/RsAddr[3]} {cpu/RsAddr[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu/ReadData1[0]} {cpu/ReadData1[1]} {cpu/ReadData1[2]} {cpu/ReadData1[3]} {cpu/ReadData1[4]} {cpu/ReadData1[5]} {cpu/ReadData1[6]} {cpu/ReadData1[7]} {cpu/ReadData1[8]} {cpu/ReadData1[9]} {cpu/ReadData1[10]} {cpu/ReadData1[11]} {cpu/ReadData1[12]} {cpu/ReadData1[13]} {cpu/ReadData1[14]} {cpu/ReadData1[15]} {cpu/ReadData1[16]} {cpu/ReadData1[17]} {cpu/ReadData1[18]} {cpu/ReadData1[19]} {cpu/ReadData1[20]} {cpu/ReadData1[21]} {cpu/ReadData1[22]} {cpu/ReadData1[23]} {cpu/ReadData1[24]} {cpu/ReadData1[25]} {cpu/ReadData1[26]} {cpu/ReadData1[27]} {cpu/ReadData1[28]} {cpu/ReadData1[29]} {cpu/ReadData1[30]} {cpu/ReadData1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {cpu/ReadData2[0]} {cpu/ReadData2[1]} {cpu/ReadData2[2]} {cpu/ReadData2[3]} {cpu/ReadData2[4]} {cpu/ReadData2[5]} {cpu/ReadData2[6]} {cpu/ReadData2[7]} {cpu/ReadData2[8]} {cpu/ReadData2[9]} {cpu/ReadData2[10]} {cpu/ReadData2[11]} {cpu/ReadData2[12]} {cpu/ReadData2[13]} {cpu/ReadData2[14]} {cpu/ReadData2[15]} {cpu/ReadData2[16]} {cpu/ReadData2[17]} {cpu/ReadData2[18]} {cpu/ReadData2[19]} {cpu/ReadData2[20]} {cpu/ReadData2[21]} {cpu/ReadData2[22]} {cpu/ReadData2[23]} {cpu/ReadData2[24]} {cpu/ReadData2[25]} {cpu/ReadData2[26]} {cpu/ReadData2[27]} {cpu/ReadData2[28]} {cpu/ReadData2[29]} {cpu/ReadData2[30]} {cpu/ReadData2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 5 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {cpu/RtAddr[0]} {cpu/RtAddr[1]} {cpu/RtAddr[2]} {cpu/RtAddr[3]} {cpu/RtAddr[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {cpu/jumpOut[0]} {cpu/jumpOut[1]} {cpu/jumpOut[2]} {cpu/jumpOut[3]} {cpu/jumpOut[4]} {cpu/jumpOut[5]} {cpu/jumpOut[6]} {cpu/jumpOut[7]} {cpu/jumpOut[8]} {cpu/jumpOut[9]} {cpu/jumpOut[10]} {cpu/jumpOut[11]} {cpu/jumpOut[12]} {cpu/jumpOut[13]} {cpu/jumpOut[14]} {cpu/jumpOut[15]} {cpu/jumpOut[16]} {cpu/jumpOut[17]} {cpu/jumpOut[18]} {cpu/jumpOut[19]} {cpu/jumpOut[20]} {cpu/jumpOut[21]} {cpu/jumpOut[22]} {cpu/jumpOut[23]} {cpu/jumpOut[24]} {cpu/jumpOut[25]} {cpu/jumpOut[26]} {cpu/jumpOut[27]} {cpu/jumpOut[28]} {cpu/jumpOut[29]} {cpu/jumpOut[30]} {cpu/jumpOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {cpu/WriteReg[0]} {cpu/WriteReg[1]} {cpu/WriteReg[2]} {cpu/WriteReg[3]} {cpu/WriteReg[4]} {cpu/WriteReg[5]} {cpu/WriteReg[6]} {cpu/WriteReg[7]} {cpu/WriteReg[8]} {cpu/WriteReg[9]} {cpu/WriteReg[10]} {cpu/WriteReg[11]} {cpu/WriteReg[12]} {cpu/WriteReg[13]} {cpu/WriteReg[14]} {cpu/WriteReg[15]} {cpu/WriteReg[16]} {cpu/WriteReg[17]} {cpu/WriteReg[18]} {cpu/WriteReg[19]} {cpu/WriteReg[20]} {cpu/WriteReg[21]} {cpu/WriteReg[22]} {cpu/WriteReg[23]} {cpu/WriteReg[24]} {cpu/WriteReg[25]} {cpu/WriteReg[26]} {cpu/WriteReg[27]} {cpu/WriteReg[28]} {cpu/WriteReg[29]} {cpu/WriteReg[30]} {cpu/WriteReg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ALUout[0]} {ALUout[1]} {ALUout[2]} {ALUout[3]} {ALUout[4]} {ALUout[5]} {ALUout[6]} {ALUout[7]} {ALUout[8]} {ALUout[9]} {ALUout[10]} {ALUout[11]} {ALUout[12]} {ALUout[13]} {ALUout[14]} {ALUout[15]} {ALUout[16]} {ALUout[17]} {ALUout[18]} {ALUout[19]} {ALUout[20]} {ALUout[21]} {ALUout[22]} {ALUout[23]} {ALUout[24]} {ALUout[25]} {ALUout[26]} {ALUout[27]} {ALUout[28]} {ALUout[29]} {ALUout[30]} {ALUout[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {DBOut[0]} {DBOut[1]} {DBOut[2]} {DBOut[3]} {DBOut[4]} {DBOut[5]} {DBOut[6]} {DBOut[7]} {DBOut[8]} {DBOut[9]} {DBOut[10]} {DBOut[11]} {DBOut[12]} {DBOut[13]} {DBOut[14]} {DBOut[15]} {DBOut[16]} {DBOut[17]} {DBOut[18]} {DBOut[19]} {DBOut[20]} {DBOut[21]} {DBOut[22]} {DBOut[23]} {DBOut[24]} {DBOut[25]} {DBOut[26]} {DBOut[27]} {DBOut[28]} {DBOut[29]} {DBOut[30]} {DBOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list CPUCLK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list cpu/sign]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets BasysCLK_IBUF_BUFG]
